dict_category = {'Machine Learning': ['machine learning', 'clustering', 'supervised', 'unsupervised', 'predictive modeling'],
                 'Deep Learning': ['deep learning', 'pytorch', 'tensorflow', 'neural networks', 'computer vision', 'opencv'],
                 'NLP': ['nlp', 'natural language processing', 'text processing', 'text analysis'],
                 'Business Intelligence': ['tableau', 'power bi', 'qlik sense'],
                 'Data Analytics': ['data analysis', 'analytics', 'visualization', 'data processing'],
                 'Cloud Computing': ['cloud computing', 'cloud-computing', ' aws ', 'azure', 'gcp', 'google cloud'],
                 'Big Data Frameworks': ['big data', 'spark', 'data lake'],
                 'Statistics': ['statistics', 'statistical'],
                 'Time Series': ['time series', 'forecasting'],
                 'Database Management': ['database management', 'data warehouse'],
                 'Data Extraction': ['data extraction', 'scraping'],
                 'Data Mining': ['data mining'],
                 'Python/R': ['python', ' r '],
                 'SQL': ['sql'],
                 'NoSQL': ['nosql', 'no-sql'],
                 'Java/JavaScript': ['java', 'javascript'],
                 'C/C++': [' c ', 'c++'],
                 'Scala': ['scala'],
                 'SAS': ['sas'],
                 'Recommendation Systems': ['recommendation systems'],
                 'MLOps': ['mlops'],
                 'DevOps': ['DevOps'],
                 'Flask': ['flask'],
                 'Optimization': ['optimization']
                 }